import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const projectRoot = resolve(import.meta.dirname, '..')

async function source(path: string) {
  return await readFile(resolve(projectRoot, path), 'utf8')
}

describe('page editor workspace contracts', () => {
  it('composes Nuxt UI editor controls through the mounted editor slot', async () => {
    const editor = await source('app/components/PageEditor.vue')
    const editorStart = editor.indexOf('<UEditor\n')
    const editorEnd = editor.indexOf('</UEditor>', editorStart)
    const editorSlot = editor.slice(editorStart, editorEnd)

    expect(editorSlot).toMatch(/v-slot="{\s*editor\s*}"/)
    expect(editorSlot).toMatch(/:items="toolbarGroups"/)
    expect(editorSlot).toMatch(/<Teleport\s+v-if="isEditing && toolbarHostRef"\s+:to="toolbarHostRef"/)
    expect(editorSlot).toMatch(/<RichEditorLinkPopover\s+:editor="editor"\s+auto-open\s+:disabled="isDisabled\(item\)"/)
    expect(editorSlot).toMatch(/<UEditorDragHandle/)
    expect(editorSlot).toMatch(/<UDropdownMenu/)
    expect(editorSlot).toMatch(/@update:open="setDragMenuOpen\(editor,\s*\$event\)"/)
    expect(editor).toMatch(/editorProfile\.quickMenuGroups\.flatMap/)
    expect(editor).toMatch(/editor\.commands\.setNodeSelection\(selected\.pos\)/)
    expect(editor).toMatch(/setMeta\('lockDragHandle',\s*open\)/)
    expect(editor).toMatch(/mapEditorItems\(editor,\s*groups\s+as\s+any,\s*editorProfile\.handlers\)/)
    expect(editor).toMatch(/getPageToolbarGroups\(\s*editorProfile\.toolbarGroups,\s*selectedBlock\.value\s*\?\s*'pageBlock'\s*:\s*null\s*\)/)
    expect(editor).not.toContain('dragHandleNestedOptions')
    expect(editorSlot).not.toContain(':nested-options=')
    expect(editor).not.toContain('label: \'Duplicate block\'')
    expect(editor).not.toContain('label: \'Move block up\'')
    expect(editor).not.toContain('label: \'Move block down\'')
    expect(editor).not.toContain('label: \'Delete block\'')
    expect(editor).toContain('<PageDocumentRenderer')
    expect(editor).toMatch(/<div\s+v-show="mode === 'edit'"/)
    expect(editor).toContain('v-show="mode === \'preview\'"')
    expect(editor).not.toContain('v-if="mode === \'edit\'"')
    expect(editor).not.toContain('transform: scale')
  })

  it('uses a full-bleed desktop canvas and framed tablet and mobile canvases', async () => {
    const editor = await source('app/components/PageEditor.vue')

    expect(editor).toContain('maxWidth: viewport.value === \'desktop\' ? \'none\'')
    expect(editor).toContain('viewport.value === \'tablet\' ? \'48rem\' : \'24rem\'')
    expect(editor).toContain('isFullWidthCanvas.value ? \'p-0\' : \'p-3 sm:p-5\'')
    expect(editor).toContain('? \'rounded-none border-0 shadow-none\'')
    expect(editor).toContain(': \'rounded-md border border-muted shadow-sm\'')
    expect(editor).toContain('class="min-h-0 flex-1 overflow-auto"')
    expect(editor).toContain('data-page-editor-canvas-shell')
    expect(editor).toContain('data-page-editor-edit-surface')
    expect(editor).toContain('data-page-editor-preview-surface')
    expect(editor).toContain('class="relative mx-auto h-full min-h-0')
    expect(editor).toContain('class="flex h-full min-h-0 w-full flex-col bg-default"')
    expect(editor).toContain(':ui="{ base: \'min-h-full px-4 py-4 sm:px-6\' }"')
    expect(editor).toContain('data-page-editor-toolbar-host')
    expect(editor.indexOf('data-page-editor-toolbar-host')).toBeLessThan(editor.indexOf('data-page-editor-canvas-shell'))
    expect(editor).toContain('sticky top-0 z-20 min-h-12 shrink-0 overflow-x-auto')
    expect(editor).toContain('min-h-12 w-max min-w-full flex-nowrap px-2 py-2')
    expect(editor).not.toContain('toolbarRadiusClass')
    expect(editor.match(/<USlideover/g)).toHaveLength(1)
    expect(editor).toContain('v-model:open="mobilePanelOpen"')
    expect(editor).toContain('aria-label="Page editor panel"')
    expect(editor).not.toContain('aria-label="Block library"')
    expect(editor).not.toContain('border-r border-muted')
    expect(editor).not.toContain('UDashboardGroup')
  })

  it('keeps Block Library and Inspector in one ordered right panel', async () => {
    const editor = await source('app/components/PageEditor.vue')
    const panel = await source('app/components/page-editor/PageEditorPanel.vue')
    const library = panel.indexOf('{ label: \'Block Library\', value: \'library\'')
    const inspector = panel.indexOf('{ label: inspectorTabLabel.value, value: \'inspector\'')

    expect(library).toBeGreaterThan(0)
    expect(inspector).toBeGreaterThan(library)
    expect(editor).toContain('const activePanel = ref<\'library\' | \'inspector\'>(\'inspector\')')
    expect(editor).toContain('if (selectedBlock.value || selectedHero.value) activePanel.value = \'inspector\'')
    expect(editor.match(/<PageEditorPanel/g)).toHaveLength(2)
    expect(panel).toContain('import PageBlockPalette from \'~/components/page-editor/PageBlockPalette.vue\'')
    expect(panel).toContain('import PageBlockInspector from \'~/components/page-editor/PageBlockInspector.vue\'')
    expect(panel).toContain('import PagePropertiesInspector from \'~/components/page-editor/PagePropertiesInspector.vue\'')
    expect(panel.match(/<UTabs/g)).toHaveLength(1)
    expect(panel.match(/<PageBlockPalette/g)).toHaveLength(1)
    expect(panel.match(/<PageBlockInspector/g)).toHaveLength(1)
    expect(panel.match(/<PagePropertiesInspector/g)).toHaveLength(1)
    expect(panel).toContain('activeTab.value === \'inspector\' && !props.selectedBlock && !props.selectedHero ? \'Page properties\' : \'Inspector\'')
    expect(panel).toContain('list: \'min-h-12 shrink-0')
    expect(panel).toContain('trigger: \'min-h-10\'')
    expect(panel).not.toContain(':unmount-on-hide="false"')
    expect(editor).toContain('if (!isEditMode.value || panelCollapsed.value) return \'lg:grid-cols-1\'')
    expect(editor).toContain('return \'lg:grid-cols-[minmax(0,1fr)_22rem]\'')
    expect(editor).toContain('class="hidden min-h-0 border-l border-muted bg-default lg:flex lg:flex-col"')
    expect(editor).toContain('if (!isEditMode.value) return')
    expect(editor).toContain('v-if="isEditMode && !panelCollapsed"')
  })

  it('uses one icon-only DashboardToolbar toggle for the desktop panel and small-screen drawer', async () => {
    const editor = await source('app/components/PageEditor.vue')
    const panel = await source('app/components/page-editor/PageEditorPanel.vue')
    const toolbarStart = editor.indexOf('<UDashboardToolbar>')
    const toolbarEnd = editor.indexOf('</UDashboardToolbar>', toolbarStart)
    const toolbar = editor.slice(toolbarStart, toolbarEnd)
    const leftSlot = toolbar.slice(toolbar.indexOf('<template #left>'), toolbar.indexOf('<template #right>'))
    const rightSlot = toolbar.slice(toolbar.indexOf('<template #right>'))

    expect(editor.match(/<UDashboardToolbar>/g)).toHaveLength(1)
    expect(leftSlot).toContain('<UFieldGroup')
    expect(leftSlot).toContain('aria-label="Canvas viewport"')
    expect(leftSlot).toContain('data-page-editor-viewport-group')
    expect(leftSlot).toContain(':ui="{ label: \'hidden lg:inline\' }"')
    expect(rightSlot).not.toContain('aria-label="Canvas viewport"')
    expect(rightSlot).toContain('data-page-editor-panel-toggle')
    expect(rightSlot).toContain('aria-label="Toggle page editor panel"')
    expect(rightSlot).toContain('icon="i-lucide-panel-right"')
    expect(editor.match(/data-page-editor-panel-toggle/g)).toHaveLength(1)
    expect(editor).toContain('const desktopPanelMediaQueryText = \'(min-width: 1024px)\'')
    expect(editor).toContain('window.matchMedia(desktopPanelMediaQueryText).matches')
    expect(editor).toContain('addEventListener(\'change\', handlePanelBreakpointChange)')
    expect(editor).toContain('if (event.matches) mobilePanelOpen.value = false')
    expect(editor).toContain('panelCollapsed.value = !panelCollapsed.value')
    expect(editor).toContain('mobilePanelOpen.value = !mobilePanelOpen.value')
    expect(editor).toContain('meta_shift_b: () => openPanel(\'library\')')
    expect(editor).toContain('meta_shift_i: () => openPanel(\'inspector\')')
    expect(editor).not.toContain('label="Editor panel"')
    expect(editor).not.toContain('Expand page editor panel')
    expect(editor).not.toContain('grid-cols-[minmax(0,1fr)_3rem]')
    expect(editor).not.toContain('collapsible')
    expect(editor).not.toContain('@collapse=')
    expect(panel).not.toContain('collapsible')
    expect(panel).not.toContain('<template #list-trailing>')
  })

  it('provides explicit palette search keys and shared pointer, keyboard, and touch insertion', async () => {
    const palette = await source('app/components/page-editor/PageBlockPalette.vue')
    const editor = await source('app/components/PageEditor.vue')
    const insertion = await source('app/editor/page/insertion.ts')

    expect(palette).toContain('keys: [\'label\', \'summary\', \'category\', \'keywords\']')
    expect(palette).toContain('onSelect: () => emit(\'insert\', { model: item.model, source: item.source, key: item.key }')
    expect(palette).toContain('@dragstart="emit(\'dragstart\'')
    expect(palette).toContain('...pagePatternRegistry.patterns.map')
    expect(editor).toContain('application/x-halopress-page-library')
    expect(editor).toContain('editor.view.posAtCoords')
    expect(editor).toContain('editor.commands.insertPageBlockAt')
    expect(editor).toContain('editor.commands.insertPagePatternAt')
    expect(editor.match(/finishPageLibraryInsertion\(editor\)/g)).toHaveLength(2)
    expect(editor).toContain('if (!closingMobilePanel) focusPageLibraryInsertion(editor)')
    expect(editor).toContain('event.preventDefault()')
    expect(editor).toContain('focusPageLibraryInsertion(getEditor())')
    expect(insertion).toContain('editor?.view.focus()')
    expect(editor).toContain(':content="{ onCloseAutoFocus: handleMobilePanelCloseAutoFocus }"')
    expect(editor.match(/scrollPageContentIntoView\(editor, destination\)/g)).toHaveLength(2)
    const dropHandler = editor.indexOf('function handleCanvasDrop(event: DragEvent)')
    expect(editor.indexOf('event.preventDefault()', dropHandler))
      .toBeLessThan(editor.indexOf('const position = dropPosition.value', dropHandler))
  })

  it('keeps block actions live-selection based and inspector updates focus safe', async () => {
    const editor = await source('app/components/PageEditor.vue')
    const panel = await source('app/components/page-editor/PageEditorPanel.vue')
    const inspector = await source('app/components/page-editor/PageBlockInspector.vue')

    expect(editor).toContain('editor.commands.updatePageBlockAttributes(attrs)')
    expect(editor).toContain('editor.commands.updatePageHeroAttributes(attrs)')
    expect(editor).toContain('editor.commands.convertLegacyPageHeroBlock()')
    expect(editor).toContain('clonePageBlockAttrs(node.attrs as PageBlockAttrs)')
    expect(editor).not.toContain('structuredClone(node.attrs as PageBlockAttrs)')
    expect(editor).toContain('clearPageBlockSelection(editor)')
    expect(panel).toContain('label="Page properties"')
    expect(panel).toContain('label="Convert to editable Hero"')
    expect(editor).not.toContain('selectedBlock.value.pos')
    expect(inspector).toContain('<CmsAssetPicker v-model="selectedAssetId"')
    expect(inspector).toContain('Move link up')
    expect(inspector).toContain('field.type === \'object-list\'')
    expect(inspector).toContain('[\'select\', \'color-token\', \'spacing\'].includes(itemField.type)')
    expect(inspector).toContain('Portable JSON only')
  })

  it('composes page metadata into the default Inspector without changing route-page ownership', async () => {
    const panel = await source('app/components/page-editor/PageEditorPanel.vue')
    const properties = await source('app/components/page-editor/PagePropertiesInspector.vue')
    const metadata = await source('app/components/cms/PublicMetadataFields.vue')
    const assetPicker = await source('app/components/cms/AssetPicker.vue')
    const palette = await source('app/components/page-editor/PageBlockPalette.vue')
    const createPage = await source('app/pages/_desk/pages/new.vue')
    const editPage = await source('app/pages/_desk/pages/[id].vue')

    for (const page of [createPage, editPage]) {
      expect(page).toContain('v-model:page-title="state.title"')
      expect(page).toContain('v-model:public-path="state.publicPath"')
      expect(page).toContain('v-model:description="state.description"')
      expect(page).toContain('v-model:social-image-asset-id="state.socialImageAssetId"')
      expect(page).not.toContain('v-model:seo-title=')
      expect(page).not.toContain('v-model:structured-data-type=')
      expect(page).not.toContain('title: state.seoTitle')
      expect(page).toContain('import { derivePublicSeoTitle } from \'~~/shared/public-seo\'')
      expect(page).toContain('title: derivePublicSeoTitle(state.title)')
      expect(page).toContain('description: state.description || undefined')
      expect(page).toContain('imageAssetId: state.socialImageAssetId || undefined')
      expect(page).toContain('structuredDataType: state.structuredDataType || undefined')
      expect(page).not.toContain('<CmsPublicMetadataFields')
      expect(page).toContain('publicMetadataPayload()')
    }
    expect(panel).toContain('<PagePropertiesInspector')
    expect(properties).not.toContain('<CmsPublicMetadataFields')
    expect(properties).not.toContain('<h2')
    expect(properties).not.toContain('SEO Title')
    expect(properties).not.toContain('Structured data type')
    expect(properties).not.toContain('validationMessage')
    expect(properties).not.toContain('<UAlert')
    expect(properties).toContain('label="Title"')
    expect(properties).toContain('label="Description"')
    expect(properties).toContain('label="Canonical path"')
    expect(properties).toContain('<CmsAssetPicker')
    expect(properties).toContain('label="Social image"')
    expect(properties.indexOf('label="Title"')).toBeLessThan(properties.indexOf('label="Description"'))
    expect(properties.indexOf('label="Description"')).toBeLessThan(properties.indexOf('label="Canonical path"'))
    expect(properties.indexOf('label="Canonical path"')).toBeLessThan(properties.indexOf('<CmsAssetPicker'))
    expect(palette).toContain('<section aria-label="Block Library"')
    expect(palette).not.toContain('<h2')
    expect(assetPicker).toContain('disabled?: boolean')
    expect(assetPicker).toContain(':disabled="disabled || uploading"')
    expect(assetPicker).toContain(':interactive="!disabled && !uploading"')
    expect(metadata).toContain('const schemaDefaultValue = \'__schema_default__\'')
    expect(metadata).toContain('value === schemaDefaultValue ? \'\' : value')
    expect(metadata).toContain('v-model="structuredDataTypeValue"')
    expect(metadata).not.toContain('{ label: \'Schema default\', value: \'\' }')
    expect(metadata.match(/:class="{ 'md:col-span-2': !compact }"/g)).toHaveLength(3)
    expect(editPage).toContain(':editable="!isDeleted"')
    expect(panel).toContain(':disabled="!props.editable"')
    expect(panel).toContain('v-if="pageValidationMessage"')
    expect(panel).toContain(':description="pageValidationMessage"')
    expect(panel.indexOf('v-if="pageValidationMessage"')).toBeLessThan(panel.indexOf('<PageBlockInspector'))
    expect(panel.indexOf('v-if="pageValidationMessage"')).toBeLessThan(panel.indexOf('<PagePropertiesInspector'))
  })

  it('offers explicit blank and reviewed starter choices only on new pages', async () => {
    const createPage = await source('app/pages/_desk/pages/new.vue')
    const editPage = await source('app/pages/_desk/pages/[id].vue')

    expect(createPage).toContain('data-page-starter-choices')
    expect(createPage).toContain('chooseStarter(\'blank\')')
    expect(createPage).toContain('chooseStarter(\'starter\')')
    expect(createPage).toContain('buildPageDocumentFromPattern(\'starter-page\')')
    expect(createPage).toMatch(/const\s+hasStarterChoice\s*=\s*computed\(\(\)\s*=>\s*starterChoice\.value\s*!==\s*null\)/)
    expect(createPage).toMatch(/hasStarterChoice\.value\s*&&\s*isDirty\.value/)
    expect(createPage).toMatch(/if\s*\(\s*!canSaveDraft\.value\s*\)\s*return/)
    expect(createPage).toMatch(/if\s*\(\s*!canPublish\.value\s*\)\s*return/)
    expect(createPage).toContain('validatePageDocumentForPublication(state.content)')
    expect(editPage).toContain('validatePageDocumentForPublication(state.content)')
    expect(createPage).toContain(':page-validation-message="publishValidationIssues[0]?.message"')
    expect(editPage).toContain(':page-validation-message="publishValidationIssues[0]?.message"')
    expect(editPage).not.toContain('data-page-starter-choices')
  })
})
