import { mkdir, readFile, stat, unlink, writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { dirname, join } from 'node:path'
import type { H3Event } from 'h3'

import { getTenantKey } from '../utils/tenant'

export function assetObjectKey(event: H3Event, assetId: string) {
  const tenantKey = getTenantKey(event)
  return `t/${tenantKey}/assets/${assetId}/orig`
}

function localPathForObjectKey(objectKey: string) {
  return join(process.cwd(), '.data', 'r2', ...objectKey.split('/'))
}

function getR2Bucket(event: H3Event) {
  const cf = (event as any).context?.cloudflare
  // ASSETS is reserved for the Worker static assets binding generated by Nitro.
  const bucket = cf?.env?.CONTENT_ASSETS ?? cf?.env?.R2 ?? null
  if (cf && !bucket) {
    throw new Error('Missing Cloudflare R2 binding: CONTENT_ASSETS')
  }
  return bucket
}

export async function putObject(event: H3Event, objectKey: string, bytes: Uint8Array, contentType: string) {
  const bucket = getR2Bucket(event)
  if (bucket) {
    await bucket.put(objectKey, bytes, { httpMetadata: { contentType } })
    return
  }

  const path = localPathForObjectKey(objectKey)
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, bytes)
}

export async function getObject(event: H3Event, objectKey: string): Promise<{
  bytes: Uint8Array
  contentType?: string
  identity: string
} | null> {
  const bucket = getR2Bucket(event)
  if (bucket) {
    const obj = await bucket.get(objectKey)
    if (!obj) return null
    const bytes = new Uint8Array(await obj.arrayBuffer())
    const ct = (obj as any).httpMetadata?.contentType
    const identity = typeof (obj as any).httpEtag === 'string' && (obj as any).httpEtag
      ? (obj as any).httpEtag
      : createHash('sha256').update(bytes).digest('hex')
    return { bytes, contentType: ct, identity }
  }

  const path = localPathForObjectKey(objectKey)
  try {
    const bytes = new Uint8Array(await readFile(path))
    return {
      bytes,
      identity: createHash('sha256').update(bytes).digest('hex')
    }
  } catch {
    return null
  }
}

export async function getObjectSize(event: H3Event, objectKey: string) {
  const bucket = getR2Bucket(event)
  if (bucket) {
    const obj = await bucket.head(objectKey)
    return (obj as any)?.size ?? null
  }

  try {
    const s = await stat(localPathForObjectKey(objectKey))
    return s.size
  } catch {
    return null
  }
}

export async function deleteObject(event: H3Event, objectKey: string) {
  const bucket = getR2Bucket(event)
  if (bucket) {
    await bucket.delete(objectKey)
    return
  }

  try {
    await unlink(localPathForObjectKey(objectKey))
  } catch {
    // ignore missing files
  }
}
